
### GET 포인트 조회
GET {{root-path}}/api/v1/users/1/points

### POST 포인트 충전
POST {{root-path}}/api/v1/users/1/points
Content-Type: application/json
Idempotency-Key: 2024121718210034623

{
  "chargeAmount": "1000.0"
}
