INSERT INTO USERS (ID, NAME, POINT) VALUES (1, '일광호', 1000000);
INSERT INTO USERS (ID, NAME, POINT) VALUES (2, '이광호', 1000000);
INSERT INTO USERS (ID, NAME, POINT) VALUES (3, '삼광호', 1000000);
INSERT INTO USERS (ID, NAME, POINT) VALUES (4, '사광호', 1000000);
INSERT INTO USERS (ID, NAME, POINT) VALUES (5, '오광호', 1000000);
INSERT INTO USERS (ID, NAME, POINT) VALUES (6, '육광호', 1000000);

INSERT INTO PRODUCT (ID, PRODUCT_NAME, PRICE) VALUES (1, '토마토 파스타', 2000);
INSERT INTO PRODUCT (ID, PRODUCT_NAME, PRICE) VALUES (2, '아이폰17 PRO', 5000);
INSERT INTO PRODUCT (ID, PRODUCT_NAME, PRICE) VALUES (3, '빽다방 아메리카노', 1500);

INSERT INTO PRODUCT_STOCK (PRODUCT_ID, STOCK) VALUES (1, 10);
INSERT INTO PRODUCT_STOCK (PRODUCT_ID, STOCK) VALUES (2, 20);
INSERT INTO PRODUCT_STOCK (PRODUCT_ID, STOCK) VALUES (3, 30);

-- INSERT INTO ORDERS (ID, USER_ID) VALUES (1, 1);
--
-- INSERT INTO ORDER_ITEM (ORDER_ID, PRODUCT_ID, QUANTITY, CREATE_AT) VALUES (1, 1, 10, CURRENT_TIMESTAMP());
-- INSERT INTO ORDER_ITEM (ORDER_ID, PRODUCT_ID, QUANTITY, CREATE_AT) VALUES (1, 2, 5,  CURRENT_TIMESTAMP());

